#!/bin/bash

# Reddit 커뮤니티 시딩 가이드
# 각 커뮤니티에 가치 제공 → Threads 계정 소개로 연결

echo "=== Korea Travel 커뮤니티 시딩 가이드 ==="
echo ""
echo "목표: 첫 100명 팔로워 시드 (알고리즘 부스트용)"
echo "방법: 직접 가치 제공 → 프로필 언급 → Threads 팔로우"
echo ""
echo "1️⃣  Reddit r/korea"
echo "   Post: '첫 방문 외국인들이 놓치는 것들' 글"
echo "   내용: 각 주제별 블로그 링크 (tax refund, eSIM, T-money)"
echo "   Closing: 'More tips on Threads @solusupport_bot'"
echo ""
echo "2️⃣  Reddit r/expats"
echo "   Post: 'Korea arrival day mistakes (and how to avoid them)'"
echo "   내용: 구체적 팁 3-5개 + 블로그 링크"
echo "   CTA: 'Full guide on my Threads account'"
echo ""
echo "3️⃣  Reddit r/IAmA (Ask Me Anything setup)"
echo "   Title: 'I help first-timers avoid Korea travel mistakes — AMA'"
echo "   내용: 실제 경험담 (지어내지 말 것) → 블로그 링크"
echo ""
echo "4️⃣  Facebook Groups (Korea Expat communities)"
echo "   Platform: 'Americans in Korea', 'Digital Nomads in Seoul' 등"
echo "   내용: 같은 글을 그룹별로 맞게 리포맷"
echo ""
echo "⏰ 일정:"
echo "   - 오늘: r/korea 1개 (tax refund) + r/expats 1개 (arrival mistakes)"
echo "   - 내일: r/korea 1개 (eSIM) + Facebook Group 2개"
echo "   - 모레: r/korea 1개 (T-money) + r/expats 1개 (etiquette)"
echo ""
echo "✅ 주의사항:"
echo "   - 각 Reddit post는 '자신의 경험'처럼 쓰되, 지어내지 말 것"
echo "   - 'Join my Threads' 같은 명령조는 쓰지 말 것 (자연스럽게 언급)"
echo "   - 블로그 링크는 context.landinkorea.com/posts/... 형식"
echo "   - 첫 댓글에 빠르게 답장 (3시간 내) → 가시도 올림"
echo ""
echo "🎯 성공 지표:"
echo "   - 첫 3일간 50+명 팔로워 증가 예상"
echo "   - Reddit post당 평균 20-30 upvotes"
echo "   - Threads 프로필 방문 → 팔로우 전환율 30-50%"
